import type { Story } from '../types';

export const india: Story = {
  id: 'india',
  title: 'Incredible\nIndia',
  sub: 'Diversity & Richness',
  blurb: 'Mountains, monsoons, a hundred tongues and every festival under the sun.',
  cloth: '#a4245a',
  gold: '#f5d680',
  ink: '#2f1f27',
  pal: ['#f08a24', '#2f9a6a', '#d9326f', '#2f8fb0', '#e8c02e'],
  emblem: 'mandala',
  parts: [
    [1, 'The Land'],
    [10, 'The People'],
    [19, 'Arts and Crafts'],
    [28, 'Food and Festivals'],
    [38, 'Wisdom and Ingenuity'],
    [46, 'One Nation'],
  ],
  pages: [
    ['Prologue', 'A Civilisation of Civilisations', "One country, 28 states, 22 official languages, thousands of dialects and every major faith. Its diversity is not a problem to solve but a treasure to celebrate.", 'mandala sun'],
    ['North', 'The Himalayas', "Rising in the north, the world's youngest great mountain range feeds rivers, shelters monasteries and frames India's story.", 'peak stars'],
    ['The Plains', 'The Indo-Gangetic Plain', "The Ganga and Yamuna carry silt across fertile land that feeds hundreds of millions. Cities like Varanasi have been inhabited for thousands of years.", 'temple waves sun'],
    ['West', 'The Thar Desert', "Golden dunes, camel caravans and the forts of Rajasthan. Women's colourful dress stands out against the sand.", 'camel fort sun'],
    ['South', 'Peninsula and Western Ghats', "Monsoon forests, tea and spice hills. Kerala's backwaters and Karnataka's coffee estates flourish here.", 'palm tea hills'],
    ['East', 'The Brahmaputra and the Northeast', "Seven sister states, each with its own tribes, music and crafts. The Brahmaputra floods and nourishes Assam's tea gardens.", 'tiger forest waves'],
    ['The Coast', 'Seven Thousand Kilometres of Shore', "Fishing villages, ancient ports and golden beaches ring the peninsula from Gujarat to Bengal. Trade with Rome, Arabia and China began here.", 'ship waves palm'],
    ['Seasons', 'The Monsoon', "Every June, rain-bearing winds arrive from the Arabian Sea. The monsoon decides harvests, poems and festivals.", 'clouds drop'],
    ['Wildlife', 'Tigers, Elephants and Peacocks', "India shelters Bengal tigers, Asian elephants, one-horned rhinos, snow leopards and the graceful national bird, the peacock.", 'tiger elephant peacock'],
    ['Ancient Roots', 'Indus Valley to the Mauryas', "From Harappa's cities to Ashoka's edicts carved in stone, the subcontinent has been home to great civilisations.", 'chakra fort'],
    ['Kingdoms', 'Empires of the South', "The Cholas sailed to Southeast Asia, the Vijayanagara empire built Hampi, and Pallava sculptors carved temples from rock.", 'temple ship waves'],
    ['The Mughals', 'Domes and Gardens', "The Mughals blended Persian and Indian styles in forts, gardens and the Taj Mahal, built by Shah Jahan in memory of Mumtaz Mahal.", 'dome moon stars'],
    ['Faiths', 'Many Paths to the Divine', "Hinduism, Buddhism, Jainism and Sikhism were born here. Islam, Christianity, Judaism and Zoroastrianism found warm homes too.", 'lotus crescent cross'],
    ['Languages', 'A Country of Many Tongues', "Hindi, Bengali, Tamil, Telugu, Marathi, Urdu, Kannada, Malayalam, Odia, Punjabi and many more. Some literary traditions are over 2,000 years old.", 'book scroll'],
    ['Cities', 'Mumbai, Delhi, Kolkata, Chennai', "Each metropolis has its own rhythm: Mumbai's hustle, Delhi's history, Kolkata's literature and Chennai's classical culture.", 'skyline sun'],
    ['Villages', 'The Heart of India', "Nearly two-thirds of Indians live in villages, where festivals, fairs, weaving and farming shape the year.", 'hut wheat sun'],
    ['Tribes', 'The Adivasi Heritage', "From the Gonds and Santhals to the Nagas and Bhils, indigenous communities hold ancient songs, art and forest knowledge.", 'tree tabla'],
    ['The Soul of India', 'Hospitality', "Atithi Devo Bhava: the guest is God. A traveller in any village may be offered tea, a meal and a place to sit.", 'tea heart'],
    ['Dance', 'Bharatanatyam and Kathak', "Eight classical dance forms tell stories with mudras, rhythm and expression. Bharatanatyam came from Tamil temples, Kathak from the courts of the north.", 'tabla lotus'],
    ['Dance', 'Kathakali, Odissi and Garba', "Kerala's Kathakali paints faces in vivid green and red; Odissi curves like temple sculpture; Gujarat dances Garba all night.", 'mandala diya'],
    ['Music', 'Raga: Music of the Hours', "Hindustani and Carnatic traditions use ragas, each suited to a time of day or season. Sitar, sarod, veena and tabla weave the sound.", 'veena tabla'],
    ['Folk Art', 'Madhubani, Warli, Pattachitra', "Village art from Bihar's walls, Maharashtra's huts and Odisha's scrolls uses natural colours and geometric patterns.", 'peacock mandala'],
    ['Textiles', 'A Thousand Weaves', "Banarasi silk, Kanjeevaram sarees, Bandhani tie-dye, Kashmiri shawls and Khadi all come from skilled hands.", 'diamond'],
    ['Architecture', 'Temples in Stone', "Khajuraho, Konark, Meenakshi and Hampi show how each region imagined the sacred in stone.", 'temple sun'],
    ['Cinema', 'From Bollywood to Kollywood', "India makes more films than any other nation, in dozens of languages. Songs, dance and drama weave together.", 'camera stars'],
    ['Literature', 'From Kalidasa to Tagore', "Sanskrit epics, Sangam poetry, Bhakti verses and modern novels. Tagore became Asia's first Nobel laureate in literature, in 1913.", 'book feather'],
    ['Games', 'Chess, Kabaddi and Cricket', "Chess began as chaturanga here; kabaddi and kho-kho are home-grown, and cricket is a national passion.", 'cricket sun'],
    ['Spices', 'Spices of the World', "Pepper from Kerala, saffron from Kashmir, turmeric, cardamom and cloves: spices that once drew ships across oceans.", 'spice ship'],
    ['On the Plate', 'North and South', "Naan, dal and paneer in the north; dosa, idli and sambar in the south. Fish curry in Bengal, dhokla in Gujarat and vada pav in Mumbai.", 'spice tea'],
    ['Chai', 'Tea on Every Corner', "Whether Darjeeling, Assam or roadside masala chai, tea brings neighbours and strangers together.", 'tea clouds'],
    ['Diwali', 'The Festival of Lights', "Rows of diyas, rangoli and fireworks celebrate light over darkness, and Rama's homecoming.", 'diya stars'],
    ['Holi', 'Colours of Spring', "People throw coloured powder, dance and forgive old quarrels. Holi marks the end of winter and the triumph of good over evil.", 'mandala sun'],
    ['Eid', 'Eid and Shared Feasts', "After a month of Ramadan fasting, families enjoy sheer khurma and biryani in open houses where friends of every faith are welcome.", 'crescent dome stars'],
    ['Christmas', 'Christmas and Easter in India', "Goa's churches and Kerala's ancient Syrian Christian community celebrate with stars, carols and cake.", 'bethlehem palm'],
    ['Onam', "Kerala's Harvest Festival", "Flower carpets, snake-boat races and a feast on banana leaves welcome the mythical king Mahabali.", 'boat lotus waves'],
    ['Pongal', 'Harvest Thanks', "Tamil Nadu boils new rice and milk until it overflows, thanking sun and cattle. Makar Sankranti, Lohri and Bihu share the season.", 'wheat sun'],
    ['Gurpurab', 'Langar and Service', "Sikh gurdwaras feed everyone, whatever their faith or caste, at free community kitchens. Guru Nanak's birthday is celebrated with hymns.", 'diya people'],
    ['Wellbeing', 'Yoga and Ayurveda', "Yoga's postures and breathing and Ayurveda's herbal medicine have been practised for thousands of years and are loved across the world.", 'sage lotus'],
    ['Teachers', 'Buddha and Mahavira', "Two teachers of non-violence and compassion lived in ancient Bihar. Their messages spread across Asia.", 'sage tree'],
    ['Numbers', 'Mathematics and Astronomy', "Aryabhata calculated pi and the Earth's rotation; Brahmagupta set rules for zero; Kerala's school found infinite series before Europe.", 'abacus stars'],
    ['Science', 'Modern Science Leaders', "C. V. Raman won the Nobel Prize for light scattering, Ramanujan astounded Cambridge, and Homi Bhabha built an atomic energy programme.", 'microscope bulb'],
    ['Space', 'Chandrayaan and Mangalyaan', "ISRO reached Mars on its first try for less than the cost of a Hollywood film, and landed near the Moon's south pole in 2023.", 'rocket moon stars'],
    ['Rails', 'The Indian Railways', "Begun in 1853, it is one of the world's largest networks, carrying over 20 million people a day through every landscape.", 'train hills sun'],
    ['Digital', 'The Silicon Plateau and UPI', "Bengaluru's tech industry and UPI instant payments show India's digital leap, with millions of small shops and phones connected.", 'phone chip'],
    ['Green India', 'Sacred Groves and Solar Power', "Communities protected sacred forests for centuries. Today India builds some of the largest solar parks in the world.", 'tree solar sun'],
    ['Freedom', 'Independence, 1947', "After a long non-violent struggle led by Gandhi, Nehru, Patel, Ambedkar, Bose, Sarojini Naidu and many more, India became free on 15 August 1947.", 'flag sun'],
    ['The Constitution', 'We, the People', "Dr B. R. Ambedkar's drafting committee wrote a constitution guaranteeing equality and freedom. It came into force on 26 January 1950.", 'book scales'],
    ['Democracy', "The World's Largest Election", "Hundreds of millions of voters, and voting machines carried by boat, elephant and on foot to remote booths. Every vote counts.", 'people flag'],
    ['Unity', 'Unity in Diversity', "Different languages, colours and beliefs, yet one nation: the idea that shared humanity matters more than difference.", 'mandala people'],
    ['Symbols', 'Tiranga and the Ashoka Chakra', "The saffron, white and green flag carries a 24-spoke blue wheel, reminding citizens of dharma and progress.", 'flag chakra'],
    ['Youth', 'A Young Nation', "More than half of Indians are under thirty. Their ideas, start-ups, sports and art will shape the coming decades.", 'bulb stars'],
    ['Invitation', 'Come and See for Yourself', "Taste it, hear it, walk it: India is best understood by visiting with an open heart. Atithi Devo Bhava, the guest is God.", 'gate lotus sun'],
  ],
};
