import type { Story } from '../types';

export const jesus: Story = {
  id: 'jesus',
  title: 'The Story\nof Jesus',
  sub: 'From Bethlehem to the Empty Tomb',
  blurb: 'A carpenter’s son, a message of love, and a story that changed the world.',
  cloth: '#2c3e63',
  gold: '#ecd596',
  ink: '#27303f',
  pal: ['#c9a66b', '#5d84ab', '#8e9a5b', '#e3c774', '#a9745a'],
  emblem: 'bethlehem',
  parts: [
    [1, 'A World Waiting'],
    [8, 'Birth and Childhood'],
    [16, 'The Ministry Begins'],
    [24, 'Stories and Teachings'],
    [34, 'Miracles and Mercy'],
    [41, 'Jerusalem'],
    [48, 'Resurrection and Legacy'],
  ],
  pages: [
    ['Prologue', 'The Story of Jesus of Nazareth', "Born in a small Roman province, Jesus became the central figure of Christianity and one of history's most influential teachers. This is his story as the Gospels tell it.", 'sunburst book'],
    ['The Setting', 'Judea Under Rome', "Around 4 BC, Judea was ruled by Herod the Great under Roman authority. The people yearned for a promised Messiah.", 'fort hills sun'],
    ['The Promise', "The Prophets' Hope", "Isaiah and other prophets had spoken of a coming child called Wonderful Counsellor and Prince of Peace.", 'scroll stars'],
    ['The Visit', 'Gabriel and Mary', "In Nazareth a young woman named Mary was told she would bear a son, to be named Jesus. 'Let it be done to me,' she said.", 'dove stars'],
    ['The Dream', "Joseph's Decision", "Joseph, a carpenter betrothed to Mary, was troubled, until an angel in a dream told him to take her as his wife.", 'hut moon stars'],
    ['The Journey', 'Mary and Elizabeth', "Mary travelled to the hill country to visit her cousin Elizabeth, who would bear John. Elizabeth's child leapt in her womb.", 'hills heart'],
    ['The Road', 'To Bethlehem', "A census ordered by Caesar Augustus sent Joseph and Mary ninety miles south to Joseph's ancestral town.", 'road moon stars'],
    ['The Night', 'Born in a Stable', "With no room at the inn, Mary gave birth in a stable and laid her baby in a manger.", 'stable stars'],
    ['The Shepherds', 'Angels Over the Fields', "Shepherds watching their flocks were told of a saviour born that night. They hurried to see the child.", 'staff hills stars'],
    ['The Star', 'The Magi Follow the Star', "Wise men from the East followed a new star, bringing gifts of gold, frankincense and myrrh.", 'bethlehem camel'],
    ['The Flight', 'Escape to Egypt', "Warned of Herod's jealousy, Joseph took Mary and Jesus by night to Egypt. They stayed until Herod died.", 'camel moon stars'],
    ['Home', 'Growing Up in Nazareth', "Jesus grew up in a village of a few houses, learning the Scriptures and Joseph's carpentry.", 'hut tree'],
    ['The Temple', 'The Boy in the Temple', "At twelve, Jesus stayed behind in Jerusalem to talk with the teachers. His parents found him after three days: 'I must be in my Father's house.'", 'dome scroll'],
    ['The Silence', 'The Hidden Years', "The Gospels say little of the next eighteen years. He worked, prayed and grew in wisdom.", 'hourglass tree'],
    ['The Forerunner', 'John in the Wilderness', "John called the people to repent and be washed in the River Jordan. He wore camel hair and ate locusts and wild honey.", 'sage waves'],
    ['The Baptism', 'The Dove Descends', "Jesus was baptised by John in the Jordan. The heavens opened, a dove descended, and a voice said, 'This is my beloved Son.'", 'dove waves rays'],
    ['The Desert', 'Forty Days of Testing', "Jesus fasted in the wilderness, refusing the temptations of bread, power and glory.", 'peak moon'],
    ['The Call', 'Fishermen Become Followers', "By the Sea of Galilee, Jesus called Simon Peter, Andrew, James and John. 'Follow me, and I will make you fishers of people.'", 'boat fish waves'],
    ['The Twelve', 'The Disciples', "He chose twelve companions, ordinary men: fishermen, a tax collector, a zealot. They left their nets and lived on the road.", 'people road'],
    ['The Sign', 'Water into Wine at Cana', "At a wedding feast the wine ran out. Jesus asked the servants to fill jars with water, and it became wine, his first sign.", 'chalice drop'],
    ['The Sermon', 'The Sermon on the Mount', "On a hillside he taught: 'Blessed are the poor in spirit, the meek, the merciful, the peacemakers.' His words turned the world upside down.", 'sage hills sun'],
    ['The Prayer', 'Our Father', "When his disciples asked how to pray, he gave them a short prayer beginning, 'Our Father, who art in heaven.'", 'heart rays'],
    ['The Rule', 'The Golden Rule', "'Do to others as you would have them do to you.' Many traditions share this idea; he made it the heart of the law.", 'heart scales'],
    ['The Parable', 'The Good Samaritan', "A traveller was robbed and left on the road. Priests passed by, but a Samaritan, an outsider, stopped to help him. 'Go and do likewise.'", 'road people'],
    ['The Parable', 'The Prodigal Son', "A young man squandered his inheritance, then returned home in shame. His father ran to embrace him.", 'hut road heart'],
    ['The Parable', 'The Lost Sheep', "A shepherd left ninety-nine to find the one that strayed. Heaven rejoices more over one who returns.", 'staff hills'],
    ['The Parable', 'The Sower', "Some seed fell on the path, some on rock, some among thorns, but some on good soil and bore a hundredfold.", 'wheat hills sun'],
    ['The Parable', 'The Mustard Seed', "The kingdom of heaven is like a tiny seed that grows into a great tree where the birds find shelter.", 'tree bird'],
    ['The Parable', 'Wise and Foolish Builders', "One man built his house on rock, another on sand. When the storm came, only the first house stood.", 'hut clouds'],
    ['The Parable', 'The Talents', "A master entrusted coins to three servants. Two multiplied theirs; one buried his out of fear.", 'scales medal'],
    ['The Teaching', 'Consider the Lilies', "'Do not worry about tomorrow. Look at the birds of the air and the flowers of the field; your Father feeds them.'", 'lotus bird'],
    ['The Teaching', 'Love Your Enemies', "'Love your enemies and pray for those who persecute you.' It was a radical call to break the cycle of revenge.", 'heart olive'],
    ['The Teaching', 'The Greatest Commandment', "Asked which law was greatest, Jesus said: love God with all your heart, and love your neighbour as yourself.", 'heart scroll'],
    ['The Healing', 'The Paralysed Man', "Four friends lowered a paralysed man through a roof to reach Jesus. 'Rise, take up your mat, and walk.'", 'hut people'],
    ['The Calm', 'Stilling the Storm', "A squall threatened the fishing boat while Jesus slept. 'Peace, be still,' he said, and the wind dropped.", 'boat clouds waves'],
    ['The Feast', 'Feeding the Five Thousand', "Five loaves and two fish, shared among a hungry crowd, left twelve baskets of scraps.", 'loaf fish hills'],
    ['The Lake', 'Walking on Water', "In the fourth watch of the night he came to his frightened disciples, walking on the lake. Peter stepped out too, then began to sink.", 'waves moon feet'],
    ['The Sight', 'Bartimaeus Sees', "A blind beggar by the road cried out for mercy. Jesus asked what he wanted: 'Lord, let me see.' And he did.", 'eye sun'],
    ['The Outcast', 'Touching the Untouchable', "Jesus touched lepers and ate with tax collectors and sinners, welcoming those society turned away.", 'people heart'],
    ['The Friend', 'Raising Lazarus', "Jesus wept at the tomb of his friend Lazarus. Then he called, 'Lazarus, come out!' and the dead man walked free.", 'tomb sun'],
    ['The Entry', 'Palm Sunday', "Crowds spread cloaks and palm branches as Jesus rode into Jerusalem on a donkey, calling 'Hosanna!'", 'palm horse'],
    ['The Anger', 'Cleansing the Temple', "He overturned the tables of the money-changers: 'My house shall be called a house of prayer.' The authorities began to plot.", 'dome fire'],
    ['The Supper', 'The Last Supper', "On the night before his arrest he broke bread with his disciples, washed their feet and told them to love one another.", 'chalice loaf'],
    ['The Garden', 'Gethsemane', "Under the olive trees he prayed in anguish. The disciples slept. Then Judas came with soldiers.", 'olive moon stars'],
    ['The Trial', 'Before Pilate', "Condemned by the council, Jesus was brought to the Roman governor Pontius Pilate, who found no fault but gave way to the crowd.", 'throne scroll'],
    ['The Mockery', 'The Crown of Thorns', "Soldiers mocked him as king with a robe, a reed and a crown of thorns.", 'thorns'],
    ['Golgotha', 'The Crucifixion', "On a hill outside the city he was crucified between two criminals. 'Father, forgive them,' he said. 'It is finished.'", 'cross hills clouds'],
    ['The Silence', 'The Tomb Is Sealed', "Joseph of Arimathea laid him in a new tomb, and a great stone was rolled across the entrance.", 'tomb moon stars'],
    ['The Dawn', 'The Empty Tomb', "On the first day of the week the women found the stone rolled away. 'He is not here; he has risen.'", 'tomb sunburst'],
    ['The Road', 'Walking to Emmaus', "Two travellers met a stranger on the road and recognised him only when he broke bread.", 'road loaf sun'],
    ['The Commission', 'Go and Make Disciples', "Before ascending, Jesus sent his followers to all nations: 'I am with you always.' At Pentecost they were filled with courage.", 'dove fire globe'],
    ['The Legacy', 'Two Thousand Years On', "From a handful of fishermen, Christianity grew to over two billion followers, inspiring art, hospitals, schools and acts of mercy worldwide.", 'cross globe stars'],
  ],
};
