import type { Story } from '../types';

export const mahabharata: Story = {
  id: 'mahabharata',
  title: 'The\nMahabharata',
  sub: 'The Great Epic of Bharata',
  blurb: 'A family divided, a war for dharma, and a song sung on a battlefield.',
  cloth: '#7b1f24',
  gold: '#e8be68',
  ink: '#2e1d1a',
  pal: ['#e08a2e', '#b8332e', '#3f4f8f', '#d9a93c', '#7a3b6b'],
  emblem: 'chariot',
  parts: [
    [1, 'Origins'],
    [11, 'Rivals Rise'],
    [21, 'The Dice Game'],
    [28, 'Exile'],
    [35, 'The Road to War'],
    [41, 'Kurukshetra'],
    [49, 'Aftermath'],
  ],
  pages: [
    ['Prologue', 'The Great Epic of Bharata', "Composed by the sage Vyasa, the Mahabharata is among the longest poems ever written. It tells of duty, family, war and one question: what is dharma?", 'book lotus'],
    ['Ancestors', 'Shantanu and Ganga', "King Shantanu married the river goddess Ganga on one condition: he must never question her. Their eighth son, Devavrata, would become the great Bhishma.", 'drop crown waves'],
    ['The Vow', "Bhishma's Terrible Promise", "So that his father could marry Satyavati, Devavrata vowed to give up the throne and never marry. The gods rained flowers and named him Bhishma, 'the terrible'.", 'crown sun'],
    ['Dynasty', 'Vyasa and the Heirs', "After Shantanu's line faltered, Vyasa fathered Dhritarashtra, Pandu and Vidura. Dhritarashtra was born blind, so Pandu took the throne.", 'sage tree'],
    ['The Curse', "Pandu's Curse", "Pandu accidentally killed a sage disguised as a deer, and was cursed to die if he ever embraced his wives. He retired to the forest.", 'deer forest moon'],
    ['The Boon', "Kunti's Mantra", "Kunti knew a mantra that could call any god. Through it she bore Yudhishthira, Bhima and Arjuna; Madri bore the twins Nakula and Sahadeva.", 'sunburst lotus'],
    ['The Secret', 'The Child Named Karna', "As a girl Kunti tried the mantra and called the Sun. Her child Karna was set afloat in a basket and raised by a charioteer.", 'boat waves sun'],
    ['The Hundred', 'The Kauravas Are Born', "Gandhari, who blindfolded herself for life, bore a hundred sons and a daughter. The eldest, Duryodhana, was born amid ill omens.", 'people crown'],
    ['Youth', 'Princes of Hastinapura', "Bhima's strength and Arjuna's aim stirred Duryodhana's envy. The rivalry between cousins grew with every lesson and every game.", 'mace bow'],
    ['The Teacher', "Drona's Academy", "Drona taught the princes archery. When he asked them to hit a bird's eye, only Arjuna answered: 'I see only the eye.'", 'bow bird tree'],
    ['Tournament', 'Karna Appears', "At the tournament Karna matched Arjuna's feats. Mocked for his birth, he was crowned king of Anga by Duryodhana, who won a loyal friend.", 'crown chariot sun'],
    ['A Gift', "Ekalavya's Thumb", "A forest boy taught himself archery before a clay statue of Drona. Asked for his thumb as a teacher's fee, he gave it without a word.", 'bow forest'],
    ['The Plot', 'The House of Lac', "Duryodhana built a palace of flammable lac for the Pandavas. Warned by Vidura, they escaped through a tunnel as it burned.", 'fire fort'],
    ['Exile', 'Into the Forest', "Disguised as Brahmins, the Pandavas wandered forests and villages. Bhima slew the demon Hidimba and married his sister.", 'people tree forest'],
    ['The Slayer', 'Bhima and Baka', "A demon demanded a villager and a cartload of food every week. Bhima ate the feast himself and defeated the demon to free the village.", 'mace hut'],
    ['The Contest', "Draupadi's Swayamvara", "King Drupada's daughter would marry whoever strung a mighty bow and hit a spinning fish through its reflection. Arjuna alone succeeded.", 'bow fish'],
    ['The Union', 'Five Husbands, One Queen', "Kunti told her sons to share whatever they had brought home, not knowing it was a bride. Draupadi became wife to all five Pandavas.", 'people lotus'],
    ['The Partition', 'Indraprastha Rises', "Dhritarashtra gave the Pandavas a wasteland. With Krishna's help they built the glittering city of Indraprastha.", 'fort sun'],
    ['A Friend', 'Krishna Arrives', "Krishna, prince of Dwarka and Kunti's nephew, became the Pandavas' friend, guide and charioteer. He plays the flute, and he plays the game of fate.", 'flute feather'],
    ['Glory', 'The Rajasuya', "Yudhishthira's imperial sacrifice made him emperor of the world. Kings brought tribute, but Duryodhana burned with jealousy.", 'throne crown'],
    ['The Palace', 'The Palace of Illusions', "The Pandava palace was so magical that Duryodhana mistook marble for water and water for marble. Draupadi's laughter became a fatal insult.", 'dome waves'],
    ['The Scheme', "Shakuni's Challenge", "Shakuni, Duryodhana's uncle, invited Yudhishthira to a game of dice. The dice were loaded, and Yudhishthira could not refuse a challenge.", 'dice'],
    ['The Loss', 'Everything Wagered', "Yudhishthira lost his treasure, his kingdom, his brothers, himself and finally Draupadi. Every stake made the next seem safer.", 'dice throne'],
    ['The Shame', 'The Sari That Never Ended', "Draupadi was dragged into the hall and insulted. She cried out for justice, and Krishna answered: her sari never ran out.", 'diamond lotus'],
    ['The Vows', 'Oaths of Vengeance', "Bhima vowed to break Duryodhana's thigh; Arjuna swore to slay Karna. Draupadi left her hair unbound until the insult was avenged.", 'mace fire'],
    ['Reprieve', 'Dhritarashtra Relents', "Frightened by omens, the blind king restored the Pandavas' freedom. But Duryodhana soon tricked them into a second game.", 'dice scroll'],
    ['The Terms', 'Thirteen Years Away', "The loser must spend twelve years in the forest and live unrecognised in the thirteenth. The Pandavas set off with Draupadi.", 'road forest'],
    ['The Forest', 'Twelve Years in the Woods', "Sages told stories beside their fires, among them those of Nala and Damayanti and of Savitri. The Pandavas learned patience.", 'fire tree moon'],
    ['The Quest', "Arjuna's Celestial Weapons", "Arjuna meditated to please Shiva, who appeared as a hunter and tested him. Pleased, Shiva gave him the Pashupata weapon.", 'trident bow mountains'],
    ['Heaven', "Indra's Court", "In heaven Arjuna learned music and dance and gained divine weapons. The celestial dancer Urvashi cursed him when he declined her love.", 'lotus stars'],
    ['The Test', "The Yaksha's Questions", "By a lake, a yaksha challenged Yudhishthira with riddles. His wise answers revived his brothers, who had died drinking the water.", 'sage waves'],
    ['The Gift', "Karna's Armour", "Indra, disguised as a Brahmin, begged for Karna's natural armour and earrings. Karna gave them, knowing the cost, because he never refused a request.", 'shield sunburst'],
    ['Hidden', "The Year in Virata's Court", "Yudhishthira, Bhima, Arjuna, the twins and Draupadi served King Virata in disguise. Bhima killed Kichaka, who had insulted Draupadi.", 'crown people'],
    ['The Return', 'The Pandavas Are Found', "Just as the thirteenth year ended, Arjuna defeated the Kaurava army to save Virata's cattle. Their true identity was revealed, too late for Duryodhana.", 'bow chariot'],
    ['The Envoy', "Krishna's Peace Mission", "Krishna asked for just five villages for the Pandavas. Duryodhana refused even as much land as a needle's point could cover.", 'road flute'],
    ['The Vision', 'The Universal Form', "When Duryodhana tried to arrest him, Krishna revealed his cosmic form, holding gods, worlds and time itself.", 'sunburst eye'],
    ['The Mother', 'Kunti Meets Karna', "Kunti told Karna that he was her eldest son. He would not leave Duryodhana, but promised to spare four of the Pandavas.", 'heart waves'],
    ['The Choice', "Krishna's Offer", "Krishna offered Duryodhana his whole army, or himself alone and unarmed. Duryodhana took the army; Arjuna chose Krishna.", 'chariot horse'],
    ['The Armies', 'Eighteen Akshauhinis', "Kings across India chose sides and gathered on the plains of Kurukshetra. The largest war of the ancient world was ready to begin.", 'tent elephant'],
    ['The Rules', 'Laws of War', "Both sides agreed rules: no fighting at night, no attacking the unarmed, none on those who flee. They were broken one by one.", 'scales'],
    ['The Doubt', 'Arjuna Lays Down His Bow', "Seeing teachers and kinsmen across the field, Arjuna let his bow slip from his hand. 'How can I fight those I love?' he asked.", 'bow chariot'],
    ['The Song', 'The Bhagavad Gita', "Krishna taught: do your duty without attachment to its reward. Those 700 verses became one of the world's great scriptures.", 'chakra book'],
    ['Days 1 – 10', 'Bhishma on a Bed of Arrows', "Invincible Bhishma fell when Arjuna shot through Shikhandi's shield. He lay on the arrows until he chose the day of his death.", 'arrows sun'],
    ['Days 11 – 15', 'The Fall of Drona', "Hearing that 'Ashwatthama is dead', the teacher laid down his weapons and was slain. Only an elephant of that name had been killed.", 'elephant sword'],
    ['Day 13', 'Abhimanyu in the Wheel', "Arjuna's young son entered the Chakravyuha formation but did not know the way out. Six warriors surrounded and killed him.", 'chakra sword'],
    ['Days 16 – 17', "Karna's Chariot Wheel", "Karna's wheel sank into the earth and his memory of a mighty mantra failed him. Arjuna's arrow struck him down.", 'wheel bow'],
    ['Day 18', "Duryodhana's Fall", "Bhima broke Duryodhana's thigh with his mace, fulfilling his vow. The Kaurava king lay dying beside a lake.", 'mace crown'],
    ['The Night', 'The Night Raid', "Ashwatthama killed the sleeping Pandava camp in revenge. Krishna cursed him to wander alone for three thousand years.", 'fire moon tent'],
    ['Grief', "Gandhari's Curse", "Gandhari lost all her sons. She cursed Krishna that his clan, too, would perish, and he accepted it calmly.", 'candle eye'],
    ['The Crown', 'Yudhishthira Rules', "Hollow with grief, Yudhishthira was crowned. Bhishma taught him the duties of a king from his bed of arrows.", 'throne crown'],
    ['The End', 'The Great Journey', "After thirty-six years the Pandavas gave up the throne and walked north toward the Himalayas. One by one they fell, until only Yudhishthira and a faithful dog remained.", 'peak feet stars'],
    ['The Message', 'What the Epic Teaches', "'What is here is found elsewhere; what is not here is found nowhere.' The Mahabharata holds every human struggle, and invites us to choose dharma.", 'lotus book sun'],
  ],
};
