import type { Story } from '../types';

export const ramayana: Story = {
  id: 'ramayana',
  title: 'The\nRamayana',
  sub: 'The Journey of Rama',
  blurb: 'Exile, abduction, a bridge across the sea, and the homecoming of light.',
  cloth: '#1f5c52',
  gold: '#efcf7e',
  ink: '#1e2b27',
  pal: ['#3f9a7a', '#e5963a', '#d9647f', '#4e8fb5', '#c9b23f'],
  emblem: 'bow',
  parts: [
    [1, 'Ayodhya Begins'],
    [11, 'The Banishment'],
    [20, 'The Forest'],
    [28, 'Kishkindha'],
    [34, 'Sundara Kanda'],
    [39, 'The Great War'],
    [46, 'Homecoming'],
  ],
  pages: [
    ['Prologue', "Valmiki's Song", "The sage Valmiki, moved by sorrow at a hunter's arrow, found himself speaking in verse. So was born the first poem, the Ramayana.", 'book sun'],
    ['Ayodhya', 'The City of Kosala', "On the banks of the Sarayu lay Ayodhya, a city of broad roads, gardens and justice, ruled by the wise King Dasharatha.", 'fort waves'],
    ['Longing', 'A King Without an Heir', "Dasharatha had three queens and no sons. On the advice of sage Rishyashringa he held a great fire sacrifice, and a divine bowl of sweet payasam rose from the flames.", 'fire chalice'],
    ['Birth', 'Four Princes', "Kausalya bore Rama, Kaikeyi bore Bharata, and Sumitra bore the twins Lakshmana and Shatrughna. Ayodhya rejoiced for days.", 'lotus sun'],
    ['Youth', 'Rama and Lakshmana', "Rama and Lakshmana grew inseparable, as did Bharata and Shatrughna. Rama was gentle, brave and humble beyond his years.", 'bow people'],
    ['Guardians', "Vishwamitra's Request", "Sage Vishwamitra asked for Rama's help to protect his rituals from demons. The boys followed him into the forest.", 'sage forest'],
    ['The Trial', 'Tataka Falls', "Rama hesitated to strike a woman, but the sage reminded him of a prince's duty to protect the innocent. The demon Tataka fell.", 'bow forest'],
    ['Mithila', "King Janaka's Garden", "In Mithila, Rama first saw Sita, found in a furrow of the earth by King Janaka. Their eyes met and neither forgot.", 'lotus sun'],
    ['The Bow', "Shiva's Bow Breaks", "Only he who could lift and string Shiva's giant bow could wed Sita. Rama drew it, and it snapped with a thunderclap.", 'bow sunburst'],
    ['The Wedding', 'Four Weddings', "Rama wed Sita, Lakshmana wed Urmila, and Bharata and Shatrughna wed Mandavi and Shrutakirti. Mithila glowed with lamps.", 'diya mandala'],
    ['The Plan', 'Rama to Be Crowned', "Dasharatha, growing old, announced that Rama would be king. All Ayodhya decorated its streets in joy.", 'crown fort'],
    ['The Whisper', "Manthara's Poison", "Kaikeyi's maid convinced her that Rama's coronation would harm Bharata. Fear and ambition clouded the queen's love.", 'eye moon'],
    ['The Boons', 'Two Promises Recalled', "Kaikeyi demanded the two boons once promised by the king: Bharata as king, and Rama exiled for fourteen years.", 'scroll crown'],
    ['Duty', 'Rama Accepts', "Rama smiled, touched his father's feet and left the palace barefoot. 'A word given must be kept,' he said.", 'feet road sun'],
    ['Companions', 'Sita and Lakshmana Follow', "Sita refused to stay behind, for a wife's place was beside her husband. Lakshmana, who could not be parted from Rama, followed too.", 'people road'],
    ['Grief', "A King's Broken Heart", "Dasharatha sank into sorrow and died calling Rama's name. Ayodhya fell silent.", 'candle moon'],
    ['The Return', 'Bharata Refuses the Crown', "Bharata came home to find his father gone and his brother exiled. He rejected his mother's bargain and set out to find Rama.", 'chariot road'],
    ['The Sandals', 'The Padukas', "Rama would not return before his vow was done. Bharata carried home Rama's sandals and placed them on the throne.", 'sandals throne'],
    ['Chitrakoot', 'A Hut of Leaves', "Rama, Sita and Lakshmana built a hut of leaves and lived simply among sages, deer and peacocks.", 'hut deer forest'],
    ['The Forest', 'Through Dandaka', "Deeper in the wilderness, sages asked Rama to protect them from the rakshasas. He promised that no one would be afraid again.", 'forest bow'],
    ['A Friend', 'Jatayu, King of Vultures', "The great vulture Jatayu, a friend of Dasharatha, offered to watch over Sita. The forest family grew.", 'bird sun'],
    ['Panchavati', 'The Hut by the Godavari', "On the banks of the Godavari they built a leaf hut at Panchavati. For years they lived in peace.", 'hut waves palm'],
    ['Shurpanakha', 'A Demon Princess', "Ravana's sister Shurpanakha fell for Rama, then raged when rejected. Lakshmana cut off her nose in defence of Sita.", 'tiger moon'],
    ['Deceit', 'The Golden Deer', "Ravana's uncle Maricha took the form of a glittering deer. Sita begged Rama to fetch it, and he followed it into the woods.", 'deer sun'],
    ['The Line', 'The Lakshmana Rekha', "Hearing Rama's voice cry out, Sita sent Lakshmana to help. He drew a circle around the hut and told her never to cross it.", 'mandala hut'],
    ['Abduction', 'Ravana Carries Sita Away', "Ravana came as a holy man. When Sita stepped out to give alms, he seized her and flew south in his chariot.", 'chariot moon clouds'],
    ['Sacrifice', "Jatayu's Last Fight", "Though old, Jatayu fought Ravana and fell wounded. He lived long enough to tell Rama which way Sita had been taken.", 'bird sword'],
    ['The Search', "Rama's Despair", "Rama and Lakshmana wandered the forest asking trees, rivers and animals for Sita. Grief and determination grew together.", 'heart forest'],
    ['Devotion', "Shabari's Berries", "The old woman Shabari tasted each berry to be sure it was sweet for Rama. He accepted them with love, for devotion matters most.", 'tree drop'],
    ['The Meeting', 'Hanuman Meets Rama', "Disguised as a Brahmin, Hanuman met the brothers near Mount Rishyamukha. Rama's gentle speech won his devotion for ever.", 'mace mountains'],
    ['The Alliance', "Sugriva's Bargain", "Rama promised to help Sugriva regain his kingdom, and Sugriva promised to send the vanara armies to find Sita.", 'crown mountains'],
    ['The Duel', 'Vali Falls', "Rama shot from hiding and felled Vali in single combat with Sugriva. Dying, Vali asked if it was justice, and Rama answered him.", 'arrows forest'],
    ['The Shore', "Sampati's Sight", "The vulture Sampati, Jatayu's brother, saw Lanka across the sea. But who could leap a hundred yojanas of ocean?", 'bird waves'],
    ['The Leap', 'Hanuman Remembers His Strength', "Reminded of his own powers, Hanuman grew mountain-tall and leapt across the ocean, overcoming every obstacle in his path.", 'mace waves sun'],
    ['Lanka', 'The Golden City', "Hanuman shrank to the size of a cat and entered Lanka's gleaming palaces, searching for Sita in every room.", 'dome moon'],
    ['Ashoka Grove', 'Sita Under the Tree', "Sita sat beneath a tree, thin and steadfast, refusing all of Ravana's offers. Hanuman gave her Rama's ring and was moved to tears.", 'tree moon'],
    ['Fire', 'Lanka Burns', "Ravana's men set Hanuman's tail alight. He leapt across the rooftops, and the golden city burned behind him.", 'fire fort'],
    ['The Report', "'I Have Seen Sita'", "Hanuman returned with Sita's jewel. Rama embraced him and said he had nothing to give but his heart.", 'diamond heart mountains'],
    ['The Bridge', 'Crossing the Sea', "Rama prayed to the ocean for three days, then raised his bow. The sea god appeared and showed a way: Nala would build a bridge.", 'bridge waves'],
    ['The Stones', 'Rama Setu Rises', "The vanaras wrote Rama's name on boulders, and the stones floated. In five days a causeway spanned the sea to Lanka.", 'bridge palm sun'],
    ['The Brother', 'Vibhishana Joins Rama', "Ravana's righteous brother warned him to return Sita, was insulted, and came to Rama for shelter. Rama welcomed him as a friend.", 'crown lotus'],
    ['The Battle', 'The Armies Meet', "Bears, monkeys and rakshasas clashed outside Lanka's gates. Nights blazed with magic weapons, and the sky rained fire.", 'arrows fort fire'],
    ['The Mountain', 'Hanuman and the Sanjeevani', "Lakshmana lay dying. Hanuman flew to the Himalayas for a healing herb, and when he could not tell which it was, he lifted the whole mountain.", 'peak mace sun'],
    ['The Duel', "Ravana's Ten Heads", "Every time Rama cut off one of Ravana's ten heads, another grew back, until he fired the Brahmastra at his heart.", 'crown bow'],
    ['Victory', 'Dawn After the War', "Ravana fell, and Lanka was given to the righteous Vibhishana. Rama had kept his promise.", 'sunburst crown'],
    ['The Trial', "Sita's Trial by Fire", "To prove her purity before all, Sita stepped into a blazing pyre. Agni, the fire god, lifted her out unharmed and declared her blameless.", 'fire lotus'],
    ['The Flight', 'The Pushpaka Vimana', "Rama, Sita, Lakshmana and their friends returned in Ravana's flying chariot, pointing out the rivers and forests of their exile.", 'chariot clouds sun'],
    ['The Reunion', "Bharata's Joy", "Fourteen years to the day, Bharata met his brother at Nandigram and carried Rama's sandals back to his feet.", 'sandals heart'],
    ['The Light', 'Diwali: A City of Lamps', "Ayodhya lit rows of clay lamps to welcome its king home. That night of lights is still celebrated as Diwali.", 'diya stars'],
    ['The Coronation', 'Rama Rajya', "Rama was crowned king. His reign, Rama Rajya, is remembered as a time of justice, peace and prosperity.", 'crown throne sun'],
    ['The Shadow', "Sita's Later Years", "Rumours led Rama to send Sita away. She lived in Valmiki's hermitage and raised twin sons, Lava and Kusha. The epic does not flinch from pain.", 'hut lotus moon'],
    ['The Legacy', 'The Story Travels', "From Thailand's Ramakien to Indonesian shadow plays, Cambodia's Reamker and village Ram Lilas across India, the story keeps being retold.", 'globe lotus stars'],
  ],
};
