import type { Story } from '../types';

export const technology: Story = {
  id: 'technology',
  title: 'Evolution\nof Technology',
  sub: 'From Stone to Silicon',
  blurb: 'Curiosity solving problems: the long road from a sharpened stone to artificial minds.',
  cloth: '#8f4a27',
  gold: '#f0d08a',
  ink: '#2a2521',
  pal: ['#2f8f9a', '#c96f3c', '#4b5fb0', '#e3b23c', '#7a8793'],
  emblem: 'gears',
  parts: [
    [1, 'First Tools'],
    [9, 'Ancient Ingenuity'],
    [17, 'Knowledge and Exploration'],
    [25, 'The Age of Machines'],
    [34, 'Atoms and Electrons'],
    [42, 'The Digital World'],
    [49, 'Now and Tomorrow'],
  ],
  pages: [
    ['Prologue', 'How Humans Invented the World', "From a sharpened stone to a pocket supercomputer, technology is the story of curiosity solving problems. Turn the pages to travel from the first spark to the age of AI.", 'bulb stars'],
    ['3.3 million years ago', 'The First Stone Tools', "Early hominins struck stones to make sharp flakes for cutting meat and plants. It was the start of a long partnership between hands and minds.", 'handaxe feet'],
    ['~1 million years ago', 'Taming Fire', "Fire gave warmth, protection and cooked food. Gathered around the flame, people shared stories and grew larger brains.", 'fire moon stars'],
    ['~40,000 BCE', 'Needles, Flutes and Art', "Bone needles sewed warm clothing, bone flutes made music, and cave walls filled with painted animals. Technology and imagination grew together.", 'flute deer'],
    ['~10,000 BCE', 'Farming Begins', "In the Fertile Crescent people planted wheat and barley and tamed animals. Villages replaced wandering camps.", 'wheat sun hills'],
    ['~8000 BCE', 'Clay and Pottery', "Fired clay pots stored grain, water and oil. Later the same kilns would smelt metal.", 'spice fire'],
    ['~3500 BCE', 'The Wheel', "Potters' wheels in Mesopotamia became cart wheels. Suddenly loads could roll across the land.", 'wheel ground'],
    ['~3300 BCE', 'The Bronze Age', "Mixing copper and tin made bronze: tools, weapons and bells stronger than stone. Whole civilisations were named for a metal.", 'sword shield'],
    ['~3200 BCE', 'Writing', "The Sumerians pressed wedge-shaped marks into clay. Records, laws and poems could now outlive their authors.", 'scroll'],
    ['~2600 BCE', 'Pyramids and Engineering', "Egyptians moved two-million-block monuments using ramps, levers and organised labour. Mathematics built mountains.", 'pyramid sun'],
    ['~2500 BCE', 'Indus Valley Cities', "Harappa and Mohenjo-daro had grid streets, brick houses and covered drains: urban planning 4,500 years ago.", 'fort waves'],
    ['~1200 BCE', 'The Iron Age', "Iron was harder to smelt than bronze, but its ore lay everywhere. Stronger ploughs and tools spread widely.", 'sword fire'],
    ['~250 BCE', 'Archimedes: Screws and Levers', "Archimedes lifted water with a turning screw and claimed that a long enough lever could move the world.", 'gears drop'],
    ['~100 BCE', 'The Antikythera Mechanism', "A bronze device of dozens of gears, found in a shipwreck, predicted eclipses and planetary positions. It is the earliest known analogue computer.", 'gears moon stars'],
    ['~100 CE', 'Paper and Printing in China', "Cai Lun refined paper; later, woodblock printing carried words farther. China also gave the world the compass and gunpowder.", 'scroll book'],
    ['~500 CE', 'Zero and Decimals', "Indian mathematicians treated zero as a number and wrote tens with place value. The idea reached Arab scholars and then Europe, making modern mathematics possible.", 'abacus sunburst'],
    ['~800 CE', 'The House of Wisdom', "In Baghdad, scholars translated and improved Greek, Indian and Persian knowledge. Algebra, optics and medicine flourished.", 'dome book'],
    ['1000s', 'Compass and Navigation', "Magnetic needles and astrolabes helped sailors cross open seas far from shore.", 'ship stars waves'],
    ['1440', "Gutenberg's Printing Press", "Movable metal type and a wine-press made books cheap. Literacy spread, and ideas travelled like never before.", 'book gears'],
    ['1543 – 1610', 'The Telescope Opens the Sky', "Copernicus moved the Earth; Galileo's telescope found moons orbiting Jupiter. Humanity's place in the cosmos changed for ever.", 'telescope moon stars'],
    ['1600s', 'Microscopes and Tiny Worlds', "Leeuwenhoek saw bacteria, and Hooke drew cells. A hidden universe of life became visible.", 'microscope drop'],
    ['1687', "Newton's Laws", "Isaac Newton explained falling apples and orbiting planets with the same mathematics. Science became a tool for prediction.", 'globe stars'],
    ['1712 – 1781', 'Steam Gains Power', "Newcomen's pump and Watt's improved engine turned fuel into motion. Factories and mines no longer needed rivers or muscle.", 'gears smoke'],
    ['1764', 'Spinning Jenny and Power Looms', "Machines spun many threads at once, and cloth poured out of factories. The Industrial Revolution began in Britain.", 'gears diamond'],
    ['1804', 'The Railway', "Trevithick, then Stephenson, put steam engines on rails. Journeys that took days took hours, and continents were stitched together.", 'train smoke'],
    ['1807', 'Steamships', "Fulton's paddle steamer and later iron hulls with propellers shortened oceans and moved millions of migrants and tonnes of goods.", 'ship smoke waves'],
    ['1837 – 1844', 'The Telegraph', "Morse code sent words along wires in seconds. News stopped travelling at the speed of a horse.", 'pole letter'],
    ['1839', 'Photography', "Daguerre and Talbot fixed images onto plates and paper. The world could now be captured in a moment.", 'camera sun'],
    ['1876', 'The Telephone', "Alexander Graham Bell's 'Mr Watson, come here' was the first sentence carried by voice along a wire.", 'phone pole'],
    ['1879', "Edison's Light Bulb", "After thousands of trials, a carbonised filament glowed for hours. Cities began to shine after dark.", 'bulb rays'],
    ['1885 – 1908', 'The Automobile', "Karl Benz built a three-wheeled motorwagen; Henry Ford's assembly line made cars affordable to ordinary families.", 'car road'],
    ['1903', 'The Wright Brothers Fly', "At Kitty Hawk, Orville flew for twelve seconds. Within sixty-six years, humans would walk on the Moon.", 'plane clouds sun'],
    ['1895 – 1901', 'Radio Waves', "Marconi sent signals across the Atlantic without wires. Broadcasting would bring one voice to millions.", 'radio stars'],
    ['1928', 'Penicillin', "Alexander Fleming noticed mould killing bacteria in a dish. Antibiotics went on to save hundreds of millions of lives.", 'microscope drop'],
    ['1936 – 1946', 'The First Computers', "Turing imagined a universal machine; the giant ENIAC filled a room and computed artillery tables in seconds.", 'computer gears'],
    ['1942 – 1954', 'Nuclear Power', "Splitting the atom released enormous energy, used first in weapons and then in reactors that light whole cities.", 'gears sunburst'],
    ['1947', 'The Transistor', "Bell Labs' tiny switch replaced bulky vacuum tubes. Every modern electronic device is built from billions of transistors.", 'chip'],
    ['1957', 'Sputnik', "The Soviet Union launched the first artificial satellite. The space race began, and with it a flood of new technologies.", 'satellite stars'],
    ['1961 – 1969', 'To the Moon', "Yuri Gagarin orbited Earth in 1961; Neil Armstrong and Buzz Aldrin walked on the Moon in 1969. 'One giant leap for mankind.'", 'rocket moon stars'],
    ['1969', 'ARPANET', "Four university computers exchanged a message: 'LO', the start of 'LOGIN', before the system crashed. It was the first step of the internet.", 'globe wire'],
    ['1971 – 1977', 'Microprocessors and Home Computers', "An entire computer on one chip led to hobbyist kits, then Apple and Microsoft. Computers left the labs and arrived on desks.", 'chip computer'],
    ['1983 – 1991', 'The Internet and the Web', "TCP/IP joined networks together, and Tim Berners-Lee invented the World Wide Web at CERN. Anyone could publish to the world.", 'globe cloud'],
    ['1990s', 'Mobile Phones', "Handsets shrank from bricks to pocket devices. Text messages and then apps changed how people connect.", 'phone'],
    ['1998 – 2006', 'Search and Social', "Google organised the web's information; Facebook, YouTube and Twitter made everyone a publisher and an audience.", 'eye globe'],
    ['2007', 'The Smartphone', "The iPhone and Android put a computer, camera, map and music player in every pocket.", 'phone camera'],
    ['1990 – 2003', 'Decoding the Genome', "The Human Genome Project mapped three billion letters of DNA, opening the door to personalised medicine and gene editing.", 'dna'],
    ['2006 – 2020', 'Cloud and Big Data', "Computing moved into vast data centres you can rent by the second. Streaming, maps and collaboration follow you everywhere.", 'cloud chip'],
    ['2010s', 'Renewable Energy', "Solar panels and wind turbines became cheaper than coal in many places, offering a way to power life without warming the planet.", 'solar sun'],
    ['2012 onward', 'Machine Learning', "Neural networks learned to recognise images, translate languages and play Go at champion level, trained on vast amounts of data.", 'eye chip'],
    ['2020s', 'Generative AI', "Systems that write, draw and code became everyday tools, raising hopes for creativity and hard questions about truth, work and ethics.", 'computer book stars'],
    ['Ahead', 'Space, Quantum and Robots', "Reusable rockets, quantum computers and robots hint at the next chapters. The limits are as much human as technical.", 'rocket satellite stars'],
    ['Reflection', 'Tools Reflect Their Makers', "Every invention from stone axe to algorithm reflects the values of the people who build and use it. The next page is yours to write.", 'bulb handaxe stars'],
  ],
};
