import type { Story } from '../types';

export const ww2: Story = {
  id: 'ww2',
  title: 'The World\nat War',
  sub: '1939 – 1945',
  blurb: 'Six years that shook the planet, from broken peace to a fragile new beginning.',
  cloth: '#3b4a3f',
  gold: '#dcc58f',
  ink: '#2b2926',
  pal: ['#8d9a7b', '#c0614a', '#6f8796', '#d8b765', '#a7a9a0'],
  emblem: 'helmet',
  parts: [
    [1, 'The Road to War'],
    [9, 'The Storm Breaks'],
    [18, 'The War Widens'],
    [28, 'The Tide Turns'],
    [37, 'Victory in Europe'],
    [47, 'The End of the War'],
  ],
  pages: [
    ['1939 – 1945', 'The World at War', "Six years, more than thirty countries and a planet changed forever. Turn these pages to follow the story from a broken peace to a fragile new beginning.", 'globe stars'],
    ['1919', 'A Peace That Did Not Hold', "The Treaty of Versailles ended the Great War but left Germany humiliated and in debt. Resentment, poverty and old rivalries became fuel for something worse.", 'scroll clouds'],
    ['1929', 'The Great Depression', "Banks failed and jobs vanished across the world. Desperate people listened to loud promises, and extremist movements rose in Europe and Asia.", 'skyline clouds'],
    ['1933', 'Hitler Takes Power', "Adolf Hitler became Chancellor of Germany and swiftly dismantled democracy. The Nazi state began rearming, censoring and persecuting its own citizens.", 'flag clouds'],
    ['1931 – 1937', 'Japan Moves on China', "Japan seized Manchuria and then launched a full invasion of China. The Nanjing massacre of 1937 showed how brutal the coming war would be.", 'map mountains'],
    ['1935 – 1936', 'Fascist Ambitions', "Mussolini's Italy invaded Ethiopia while Germany marched into the Rhineland. The League of Nations protested, but nobody stopped them.", 'tank ground'],
    ['1938', 'Appeasement at Munich', "Britain and France let Germany take the Sudetenland, hoping to keep the peace. 'Peace for our time,' said Chamberlain. It lasted less than a year.", 'letter dove'],
    ['August 1939', 'A Pact of Enemies', "Germany and the Soviet Union signed a non-aggression pact and secretly agreed to divide Poland. The last obstacle to war had vanished.", 'scroll moon stars'],
    ['1 September 1939', 'Poland Invaded', "German forces crossed the border at dawn. Britain and France declared war two days later, and the Second World War began.", 'tank plane clouds'],
    ['1939 – 1940', 'Blitzkrieg', "Tanks, dive-bombers and motorised infantry struck together with stunning speed. Poland fell in five weeks, and the world learned a new word: lightning war.", 'tank plane ground'],
    ['April – June 1940', 'The Fall of France', "Germany swept through the Netherlands and Belgium, then around the Maginot Line. Paris fell on 14 June, and France surrendered days later.", 'gate skyline smoke'],
    ['May – June 1940', 'Miracle at Dunkirk', "Destroyers, fishing boats and pleasure yachts crossed the Channel. More than 330,000 soldiers were carried home from the beaches.", 'boat waves clouds'],
    ['1940', 'Churchill Stands Alone', "Winston Churchill became prime minister, promising nothing but blood, toil, tears and sweat. Britain refused to bargain with Hitler.", 'flag clouds sun'],
    ['July – October 1940', 'Battle of Britain', "Spitfires and Hurricanes rose to meet the Luftwaffe over southern England. 'Never was so much owed by so many to so few.'", 'plane clouds sun'],
    ['1940 – 1941', 'The Blitz', "Night after night bombs fell on London, Coventry and Liverpool. Families slept in Underground stations, and the cities kept their nerve.", 'skyline smoke moon'],
    ['September 1940', 'The Axis Unites', "Germany, Italy and Japan signed the Tripartite Pact. The Axis would fight the Allies across Europe, Africa, Asia and the oceans.", 'shield stars'],
    ['1940 – 1943', 'War in the Desert', "Rommel's Afrika Korps and Montgomery's Eighth Army fought back and forth across Libya and Egypt. The turning point came at El Alamein in 1942.", 'tank camel sun'],
    ['June 1941', 'Operation Barbarossa', "Germany invaded the Soviet Union along a front nearly 3,000 kilometres long, the largest invasion in history. Millions of soldiers crossed the frontier.", 'tank forest smoke'],
    ['Winter 1941', 'The Winter Stops Them', "Snow and mud halted the Germans at the gates of Moscow. Fresh Soviet divisions from Siberia counter-attacked in bitter cold.", 'helmet stars hills'],
    ['August 1941', 'The Atlantic Charter', "Roosevelt and Churchill met aboard warships off Newfoundland and pledged freedom, self-determination and peace after victory.", 'ship waves clouds'],
    ['1939 – 1945', 'Battle of the Atlantic', "German U-boats hunted Allied convoys carrying food, fuel and troops. The longest campaign of the war decided whether Britain could survive.", 'sub waves moon'],
    ['7 December 1941', 'Pearl Harbor', "Japanese carrier aircraft struck the US fleet in Hawaii at dawn. The next day America declared war, and the conflict became truly global.", 'plane ship smoke'],
    ['1941 – 1942', 'Japan Sweeps Asia', "Within months Japan took Hong Kong, Malaya, Singapore, the Philippines and Burma. The fall of Singapore was Britain's worst military defeat.", 'map palm sun'],
    ['1941 – 1945', 'The Holocaust', "Nazi Germany murdered six million Jews and millions of others in ghettos, camps and killing fields. It stands as history's darkest warning.", 'candle stars'],
    ['June 1942', 'Midway', "American codebreakers knew where Japan would strike. Four Japanese carriers sank in a single day, and the Pacific tide turned.", 'plane ship waves'],
    ['1942 – 1943', 'Stalingrad', "Street by street, house by house, Soviet defenders ground down the German Sixth Army. Its surrender in February 1943 broke the Wehrmacht's spell.", 'helmet skyline smoke'],
    ['1939 – 1945', 'The Codebreakers', "At Bletchley Park, Alan Turing and thousands of colleagues cracked Enigma. Historians believe their work shortened the war by years.", 'gears letter'],
    ['November 1942', 'Operation Torch', "Allied troops landed in Morocco and Algeria, opening a new front in North Africa and squeezing Rommel from both sides.", 'ship palm waves'],
    ['July 1943', 'Invasion of Sicily', "Allied armies took Sicily in five weeks. Mussolini fell from power, and Italy soon changed sides.", 'tank mountains sun'],
    ['July 1943', 'Kursk', "The largest tank battle in history ended in German defeat. From now on, the Red Army advanced westward.", 'tank smoke ground'],
    ['1942 – 1945', 'Women at War', "Women built bombers, ran farms, broke codes, nursed the wounded and flew aircraft. 'Rosie the Riveter' became a symbol of a workforce reborn.", 'gears heart'],
    ['1942 – 1945', 'Resistance', "Partisans and underground networks sabotaged railways, hid families and smuggled pilots to safety across occupied Europe.", 'letter moon stars'],
    ['March – July 1944', 'The Burma Front', "Indian, British, African and Gurkha soldiers halted Japan at Kohima and Imphal in north-east India. It was the turning point in Asia.", 'helmet forest mountains'],
    ['1943 – 1945', 'Island Hopping', "American and Allied forces leapt from island to island across the Pacific, from Guadalcanal to Iwo Jima, pushing Japan's perimeter back.", 'palm boat waves'],
    ['1944', 'Bombing the Reich', "Day and night, bomber fleets struck factories, railways and cities. The campaign cost thousands of airmen and countless civilian lives.", 'plane clouds moon'],
    ['November 1943', 'The Big Three', "Roosevelt, Churchill and Stalin met at Tehran to plan the final campaigns. Yalta and Potsdam would follow.", 'map stars'],
    ['6 June 1944', 'D-Day', "More than 150,000 troops landed on five Normandy beaches, backed by thousands of ships and aircraft. It was the largest seaborne invasion ever.", 'ship boat waves'],
    ['June – August 1944', 'The Normandy Breakout', "Fighting through the sunken lanes and hedgerows was slow and brutal. By August the Allies had broken out and raced toward Paris.", 'tank tree ground'],
    ['25 August 1944', 'Paris Liberated', "French and Allied soldiers entered Paris as church bells rang. After four years of occupation, the city was free.", 'skyline flag sun'],
    ['June 1944', 'Operation Bagration', "The Red Army smashed Germany's Army Group Centre in Belarus, advancing hundreds of kilometres in a few weeks.", 'tank forest smoke'],
    ['September 1944', 'A Bridge Too Far', "Operation Market Garden dropped paratroopers into the Netherlands to seize bridges. The last, at Arnhem, could not be held.", 'parachute bridge clouds'],
    ['December 1944', 'Battle of the Bulge', "Germany's last offensive in the Ardennes surprised American troops in snow and fog. Bastogne held, and the gamble failed.", 'helmet forest stars'],
    ['1944 – 1945', 'Liberating the Camps', "Soviet and Western troops opened Auschwitz, Buchenwald, Belsen and others, finding survivors and evidence the world could not ignore.", 'candle moon'],
    ['February 1945', 'Yalta', "The Allied leaders planned the post-war order: occupation zones in Germany, free elections in Europe and a new United Nations.", 'globe scroll'],
    ['April – May 1945', 'The Fall of Berlin', "Soviet armies fought into the ruined capital. Hitler died by suicide on 30 April, and Berlin surrendered on 2 May.", 'skyline smoke flag'],
    ['8 May 1945', 'Victory in Europe', "Germany surrendered unconditionally. Crowds filled the streets of London, Paris, New York and Moscow to celebrate.", 'flag rays stars'],
    ['February – June 1945', 'Iwo Jima and Okinawa', "Fierce battles on tiny islands cost tens of thousands of lives. Everyone feared an invasion of Japan itself would be even worse.", 'flag mountains smoke'],
    ['6 and 9 August 1945', 'Hiroshima and Nagasaki', "Two atomic bombs destroyed two Japanese cities and killed well over a hundred thousand people. The nuclear age had begun.", 'mushroom clouds'],
    ['15 August 1945', 'Japan Surrenders', "Emperor Hirohito announced the surrender by radio. The formal signing took place aboard the USS Missouri on 2 September.", 'radio ship waves'],
    ['1945 – 1946', 'The Nuremberg Trials', "Nazi leaders faced judges for crimes against humanity. The trials created principles of international law still used today.", 'scales scroll'],
    ['October 1945', 'The United Nations', "Fifty nations signed the UN Charter in San Francisco, hoping that talk would replace war.", 'globe dove olive'],
    ['Remembering', 'Never Again', "An estimated 70 to 85 million people died. We remember them by telling their stories, and by choosing peace each day.", 'candle dove stars'],
  ],
};
